### ISSUE TITLE
チャットワークのバージョンアップにより本拡張が動かなくなりました

### ISSUE THREAD

**Issue by yamamoto-hiroya** [techvein/chatwork-chat-snippet-chrome-extension#1]
現在のチャットワークでこの拡張が動きません
対応の予定などあるでしょうか？

**Comment by ecoopnet** [comment]
ご報告ありがとうございます。
#2 の修正を適用してChrome拡張を更新しました。アップデートをお待ち下さい！

**Comment by yamamoto-hiroya** [comment]
拡張をアップデートしたら無事に動くことが確認できました！ご対応ありがとうございます！
プルリクも見ましたが、ついでのリファクタでvarをletにしていたりとても参考になりました👍
